GET http://localhost:3030/maTacheCreate/sdljklgjg
###
GET http://localhost:3030/maTacheFindAll
###
DELETE http://localhost:3030/maTacheDelete/24
###
GET http://localhost:3030/upDateRowTache/true/23
###
GET http://localhost:3030/upDateRowTache/false/23